---
rounds_idx: 0
reference_date_col_name: 'origin_date'
target_date_col_name: 'target_end_date'
horizon_col_name: 'horizon'
initial_checked_models: ['delphi-epicast', 'hist-avg']
initial_xaxis_range:
  - '2019-08-18'
  - '2020-03-29'
disclaimer: "This is a sandbox forecast visualization. It is not designed to support an operational hub, but instead is designed for benchmarking and research purposes."